# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target '8-3-zoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
#pod 'MCFramwork'
  pod 'AFNetworking'
  pod 'JSONKit'
  

end
